export enum Status {
  DRAFT = "DRAFT",
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  CLOSED = "CLOSED",
  POSTED = "POSTED",
  CANCELLED = "CANCELLED",
  VOID = "VOID",
}
